{"uuid": "0a2db54a-7688-46fe-b183-1dd2bd5806d6", "children": ["3270167d-2b05-4f6c-a01c-caebb808ad97", "72a0bea7-62e3-45dc-8b53-1c64fe1d4f9e", "7fad5044-931b-46e3-bb0b-2f36a21ed072", "c4d87d19-5a13-4d7b-ba4f-1c1b9fdd4e87"], "befores": [{"name": "ftp文件传输fixture", "status": "broken", "statusDetails": {"message": "NameError: name 'pVm' is not defined\n", "trace": "  File \"D:\\software\\ptyhon3.7.6_x64\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\software\\ptyhon3.7.6_x64\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\software\\ptyhon3.7.6_x64\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\SVN\\File\\测试\\III型自动化测试\\AutoProject\\2023\\Hsc3_AutoTest2023\\conftest.py\", line 30, in ftp文件传输fixture\n    if pVm.mainProgNames()[1]:\n"}, "start": 1681375963434, "stop": 1681375963434}], "start": 1681375963434, "stop": 1681375963519}