{"name": "test_冒烟测试2", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败\nassert 1 == 2", "trace": "self = <test_冒烟测试用例.Test_HSC3冒烟测试 object at 0x000001D8FE418C48>\n\n    def test_冒烟测试2(self):\n        c = 1\n        d = 2\n>       assert c==d, \"断言失败\"\nE       AssertionError: 断言失败\nE       assert 1 == 2\n\nTestcase\\V2.0\\test_冒烟测试用例.py:21: AssertionError"}, "start": 1681377143226, "stop": 1681377143226, "uuid": "5328bd34-4994-46a7-8d2a-ff9b71d62fe6", "historyId": "3fc1fbce9329459146ae79ba83137fa4", "testCaseId": "0ddc6b8db51c19f1093b1746ab97de8e", "fullName": "Testcase.V2.0.test_冒烟测试用例.Test_HSC3冒烟测试#test_冒烟测试2", "labels": [{"name": "parentSuite", "value": "Testcase.V2.0"}, {"name": "suite", "value": "test_冒烟测试用例"}, {"name": "subSuite", "value": "Test_HSC3冒烟测试"}, {"name": "host", "value": "DESKTOP-AS4K0DF"}, {"name": "thread", "value": "7956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.V2.0.test_冒烟测试用例"}]}